# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-01 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='initial_rating',
        ),
        migrations.AddField(
            model_name='player',
            name='initial_rating',
            field=models.IntegerField(default=1000),
        ),
    ]
