# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-15 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_auto_20161215_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scores.Division'),
            preserve_default=False,
        ),
    ]
