# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_auto_20160903_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='isEntered',
            field=models.BooleanField(default=False),
        ),
    ]
