# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-15 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_game_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='division',
        ),
    ]
