# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_game_isentered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='losses',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='spread',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='wins',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
