# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-15 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_remove_game_division'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([('board_num', 'round'), ('player1', 'round'), ('player2', 'round')]),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([('number', 'division')]),
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together=set([('round_number', 'division')]),
        ),
    ]
