# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_auto_20160918_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player1Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2Score',
            field=models.IntegerField(default=0),
        ),
    ]
