# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-15 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_auto_20161215_2303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Round',
            new_name='TourneyRound',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='round',
            new_name='tourney_round',
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([('player1', 'tourney_round'), ('player2', 'tourney_round'), ('board_num', 'tourney_round')]),
        ),
    ]
