# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-16 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_auto_20160918_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divID', models.CharField(max_length=100)),
                ('divNum', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scores.Division'),
        ),
        migrations.AddField(
            model_name='round',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scores.Division'),
        ),
    ]
