# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-16 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0007_auto_20161016_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='id',
        ),
        migrations.AlterField(
            model_name='division',
            name='divNum',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
